name: CI

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 3.11-1.26.3-2.1.4
            version: "3.11"
            numpy: ==1.26.3
            pandas: ==2.1.4
          - name: 3.11-latest-latest
            version: "3.11"
          - name: 3.12-latest-latest
            version: "3.12"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with: { python-version: "${{ matrix.version }}" }
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: >-
            ${{ runner.os }}-${{ matrix.version }}-${{ matrix.pandas
            }}-${{ matrix.numpy }}-pip-${{ hashFiles('**/setup.py') }}
      - run: python -m pip install --upgrade pip
      - run: pip install pandas${{ matrix.pandas }}
        if: ${{ matrix.pandas }}
      - run: pip install numpy${{ matrix.numpy }}
        if: ${{ matrix.numpy }}
      - name: Install dependencies
        env: { NODE_OPTIONS: --openssl-legacy-provider }
        run: pip install -e '.[test]'
      - name: On 3.12 install unreleased python-dateutil to avoid a warning
        if: ${{ matrix.version == '3.12' }}
        run: pip install git+https://github.com/dateutil/dateutil.git
        # see
        # https://github.com/dateutil/dateutil/pull/1285
        # https://github.com/dateutil/dateutil/issues/1314
        # https://github.com/dateutil/dateutil/pull/1130
      - name: Lint with flake8
        run: |
          flake8
      - name: Run the tests
        run: pytest -Werror
# vim: set filetype=yaml.action :
