on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: pipx run build
      - run: pipx run twine check --strict dist/*
      - run: sha256sum dist/* | tee dist_checksums.txt
      - uses: actions/upload-artifact@v4
        with: { path: "dist/\ndist_checksums.txt\n" }
  test:
    runs-on: [ubuntu-latest]
    needs: build
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 3.11-requirement
            version: "3.11"
            requirement: requirements.txt
          - name: 3.11-latest
            version: "3.11"
          - name: 3.12-latest
            version: "3.12"
            flake8: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v5
        with: { python-version: "${{ matrix.version }}" }
      - uses: actions/download-artifact@v4
        with: { name: artifact }
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: >-
            ${{ runner.os }}-${{ matrix.version }}-${{ matrix.requirement
            }}-pip-${{ hashFiles('**/setup.py') }}
      - run: python -m pip install --upgrade pip
      - run: pip install --requirement=${{ matrix.requirement }}
        if: matrix.requirement
        # python3.12 -m venv --upgrade-deps .venv ; . .venv/bin/activate
      - name: Install wheel with test extras
        run: >
          pip install "dist/qgridtrusted-$(python
          qgrid/_version.py)-py3-none-any.whl[test]"
      - name: Lint with flake8
        run: flake8
        if: matrix.flake8
      - name: On 3.12 install unreleased python-dateutil to avoid a warning
        if: matrix.version == '3.12'
        run: pip install git+https://github.com/dateutil/dateutil.git
        # see
        # https://github.com/dateutil/dateutil/pull/1285
        # https://github.com/dateutil/dateutil/issues/1314
        # https://github.com/dateutil/dateutil/pull/1130
      - run: python qgrid/tests/test_grid.py
  pypi:
    if: endswith(github.ref, '/main')
    runs-on: ubuntu-latest
    needs: [build, test]
    environment:
      name: pypi
      url: https://test.pypi.org/project/qgridtrusted/
    permissions: { id-token: write }
    steps:
      - uses: actions/download-artifact@v4
        with: { name: artifact }
      - name: Publish package distributions to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: "https://test.pypi.org/legacy/"
          print-hash: true
# vim: set filetype=yaml.action :
